[page]
q = 'QUIT'
h = 'CURSOR_LEFT' 
j = 'CURSOR_DOWN'
k = 'CURSOR_UP'
l = 'CURSOR_RIGHT'
'M-[D' = 'CURSOR_LEFT'
'M-[B' = 'CURSOR_DOWN'
'M-[A' = 'CURSOR_UP'
'M-[C' = 'CURSOR_RIGHT'
'^' = 'CURSOR_LINEBEGIN'
'$' = 'CURSOR_LINEEND'
b = 'CURSOR_PREV_WORD'
w = 'CURSOR_NEXT_WORD'
'[' = 'CURSOR_PREV_LINK'
']' = 'CURSOR_NEXT_LINK'
H = 'CURSOR_TOP'
M = 'CURSOR_MIDDLE'
L = 'CURSOR_BOTTOM'
';' = 'CURSOR_LEFT_EDGE'
'+' = 'CURSOR_VERT_MIDDLE'
'@' = 'CURSOR_RIGHT_EDGE'
C-d = 'HALF_PAGE_DOWN'
C-u = 'HALF_PAGE_UP'
C-f = 'PAGE_DOWN'
C-b = 'PAGE_UP'
'M-[6~' = 'PAGE_DOWN'
'M-[5~' = 'PAGE_UP'
'>' = 'PAGE_RIGHT'
'<' = 'PAGE_LEFT'
C-e = 'SCROLL_DOWN'
C-y = 'SCROLL_UP'
J = 'SCROLL_DOWN'
K = 'SCROLL_UP'
'('= 'SCROLL_LEFT'
')' = 'SCROLL_RIGHT'
C-m = 'CLICK'
C-j = 'CLICK'
C-l = 'CHANGE_LOCATION'
U = 'RELOAD'
r = 'REDRAW'
R = 'RESHAPE'
g = 'CURSOR_FIRST_LINE'
G = 'CURSOR_LAST_LINE'
z = 'CENTER_LINE'
C-g = 'LINE_INFO'
v = 'TOGGLE_SOURCE'

[line]
C-m = 'SUBMIT'
C-j = 'SUBMIT'
C-h = 'BACKSPACE'
'C-?' = 'BACKSPACE'
C-d = 'DELETE'
C-c = 'CANCEL'
M-b = 'PREV_WORD'
M-f = 'NEXT_WORD'
C-b = 'BACK'
C-f = 'FORWARD'
C-u = 'CLEAR'
C-k = 'KILL'
C-w = 'KILL_WORD'
C-a = 'BEGIN'
C-e = 'END'
C-v = 'ESC'
