[general]
double-width-ambiguous = false

[display]
# Options: black, red, green, yellow, blue, magenta, cyan, white, terminal
mark-color = "cyan"

[page]
q = 'quit()'
h = 'cursorLeft()' 
j = 'cursorDown()'
k = 'cursorUp()'
l = 'cursorRight()'
'M-[D' = 'cursorLeft()' 
'M-[B' = 'cursorDown()'
'M-[A' = 'cursorUp()'
'M-[C' = 'cursorRight()'
'^' = 'cursorLineBegin()'
'$' = 'cursorLineEnd()'
b = 'cursorPrevWord()'
w = 'cursorNextWord()'
'[' = 'cursorPrevLink()'
']' = 'cursorNextLink()'
H = 'cursorTop()'
M = 'cursorMiddle()'
L = 'cursorBottom()'
';' = 'cursorLeftEdge()'
'+' = 'cursorVertMiddle()'
'@' = 'cursorRightEdge()'
C-d = 'halfPageDown()'
C-u = 'halfPageUp()'
C-f = 'pageDown()'
C-b = 'pageUp()'
'M-[6~' = 'pageDown()'
'M-[5~' = 'pageUp()'
'>' = 'pageRight()'
'<' = 'pageLeft()'
C-e = 'scrollDown()'
C-y = 'scrollUp()'
J = 'scrollDown()'
K = 'scrollUp()'
'('= 'scrollLeft()'
')' = 'scrollRight()'
C-m = 'click()'
C-j = 'click()'
C-l = 'changeLocation()'
M-u = 'dupeBuffer()'
U = 'reloadPage()'
r = 'redraw()'
R = 'reshape()'
g = 'cursorFirstLine()'
G = 'cursorLastLine()'
z = 'centerLine()'
C-g = 'lineInfo()'
v = 'toggleSource()'
D = 'discardBuffer()'
',' = 'prevBuffer()'
'.' = 'nextBuffer()'
M-c = 'commandMode()'
C = 'command()'
'/' = 'isearch()'
'?' = 'isearchBack()'
n = 'searchNext()'
N = 'searchPrev()'

[line]
C-m = 'SUBMIT'
C-j = 'SUBMIT'
C-h = 'BACKSPACE'
'C-?' = 'BACKSPACE'
C-d = 'DELETE'
C-c = 'CANCEL'
M-b = 'PREV_WORD'
M-f = 'NEXT_WORD'
C-b = 'BACK'
C-f = 'FORWARD'
C-u = 'CLEAR'
C-k = 'KILL'
C-w = 'KILL_WORD'
C-a = 'BEGIN'
C-e = 'END'
C-v = 'ESC'
