[external]
tmpdir = "/tmp/cha"
editor = "vi %s +%d"

[display]
color-mode = "auto"
format-mode = "auto"
alt-screen = "auto"
highlight-color = "cyan"
double-width-ambiguous = false
minimum-contrast = 100

[[siteconf]]
url = '^ddg:'
substitute_url = '(x) => "https://lite.duckduckgo.com/lite/?kp=-1&kd=-1&q=" + x.substring(4)'

[page]
q = 'quit()'
h = 'pager.cursorLeft()' 
j = 'pager.cursorDown()'
k = 'pager.cursorUp()'
l = 'pager.cursorRight()'
'M-[D' = 'pager.cursorLeft()' 
'M-[B' = 'pager.cursorDown()'
'M-[A' = 'pager.cursorUp()'
'M-[C' = 'pager.cursorRight()'
'^' = 'pager.cursorLineBegin()'
'$' = 'pager.cursorLineEnd()'
b = 'pager.cursorPrevWord()'
w = 'pager.cursorNextWord()'
'[' = 'pager.cursorPrevLink()'
']' = 'pager.cursorNextLink()'
H = 'pager.cursorTop()'
M = 'pager.cursorMiddle()'
L = 'pager.cursorBottom()'
';' = 'pager.cursorLeftEdge()'
'+' = 'pager.cursorVertMiddle()'
'@' = 'pager.cursorRightEdge()'
C-d = 'pager.halfPageDown()'
C-u = 'pager.halfPageUp()'
C-f = 'pager.pageDown()'
C-b = 'pager.pageUp()'
'M-[6~' = 'pager.pageDown()'
'M-[5~' = 'pager.pageUp()'
'>' = 'pager.pageRight()'
'<' = 'pager.pageLeft()'
C-e = 'pager.scrollDown()'
C-y = 'pager.scrollUp()'
J = 'pager.scrollDown()'
K = 'pager.scrollUp()'
'('= 'pager.scrollLeft()'
')' = 'pager.scrollRight()'
C-m = 'pager.click()'
C-j = 'pager.click()'
M-u = 'pager.dupeBuffer()'
C-l = 'pager.load()'
C-k = 'pager.load("ddg:")'
U = 'pager.reload()'
r = 'pager.redraw()'
R = 'pager.reshape()'
C-cC-c = 'pager.cancel()'
g = 'pager.cursorFirstLine()'
G = 'pager.cursorLastLine()'
z = 'pager.centerLine()'
C-g = 'pager.lineInfo()'
v = 'pager.toggleSource()'
D = 'pager.discardBuffer()'
',' = 'pager.prevBuffer()'
'.' = 'pager.nextBuffer()'
M-c = 'pager.command()'
C = 'pager.commandMode();console.show()'
'/' = 'pager.isearchForward()'
'?' = 'pager.isearchBackward()'
n = 'pager.searchNext()'
N = 'pager.searchPrev()'
c = 'pager.peek()'
u = 'pager.peekCursor()'

[line]
C-m = 'line.submit()'
C-j = 'line.submit()'
C-h = 'line.backspace()'
'C-?' = 'line.backspace()'
C-d = 'line.delete()'
C-c = 'line.cancel()'
M-b = 'line.prevWord()'
M-f = 'line.nextWord()'
C-b = 'line.backward()'
C-f = 'line.forward()'
C-u = 'line.clear()'
C-_ = 'line.clear()'
M-k = 'line.clear()'
C-k = 'line.kill()'
C-w = 'line.clearWord()'
M-C-h = 'line.clearWord()'
'M-C-?' = 'line.clearWord()'
M-d = 'line.killWord()'
C-a = 'line.begin()'
C-e = 'line.end()'
C-v = 'line.escape()'
C-p = 'line.prevHist()'
C-n = 'line.nextHist()'
